### ISSUE TITLE
Windows Compilation Guide

### ISSUE THREAD

**Issue by SkoricIT** [mmatyas/openblok#40]
Is there any info on how to compile this on Windows or on Linux for Windows target?

**Comment by mmatyas** [comment]
There's no step by step guide, but if you're in general familiar with building C++/CMake projects on Windows, OpenBlok works similarly. You can also take a look at the `.appveyor.yml` file, which contains all the necessary calls in order to build the game.

**Comment by SkoricIT** [comment]
The appveyor build produces only an .exe file (at least online)? How do I build all files and also include the localisation?

**Comment by mmatyas** [comment]
Ah yes, the automatic release died with Travis too... will need to fix that later. Here's the latest Windows build:

[openblok.zip](https://github.com/mmatyas/openblok/files/6829422/openblok.zip)

This was built with Gettext support, and the locale directory is `data/locale/`. I assume one could just drop MO files there (eg. `data\locale\de\LC_MESSAGES\main.mo`), but not sure how to test this on Windows.

In case you wish to build it manually, you'll need Gettext (and Iconv, on which it depends), you'll need to tell CMake where it is installed, and then the build does the rest. There's probably a prebuilt Gettext for Windows, if you don't want to build it manually, but I haven't looked too hard myself. (Which is why it's not used on AppVeyor: that's there only to test MSVC builds, but the actual release is cross compiled from Linux.)

**Comment by SkoricIT** [comment]
Thanks for the build. The locale does not get loaded, unfortunately. I additionally tried putting the .pot file in the locale directory but that changed nothing.

Run from Windows Terminal with locale query:
![image](https://user-images.githubusercontent.com/1708378/126046539-bfedb9fd-6e41-4195-8584-c40652d99116.png)

Directory listing:
![image](https://user-images.githubusercontent.com/1708378/126046559-b3eb0002-be58-45bc-a0d1-4ff8ad870202.png)

**Comment by mmatyas** [comment]
There were indeed some leftover CMake issues, but it should now work fine. Tested it on Windows too, with changing the locale vars, hopefully works with the system language too.

[openblok.zip](https://github.com/mmatyas/openblok/files/6842610/openblok.zip)

**Comment by mmatyas** [comment]
Fixed some accented character issues, added a Windows target to the GitHub Actions build, tested and working on Windows:

![image](https://user-images.githubusercontent.com/4354863/126499589-6bdd2a19-c741-4329-8a24-fc506876ded5.png)

**Comment by SkoricIT** [comment]
That look great, will test as soon as possible. Thank you for your effort, it is greatly appreciated!

**Comment by SkoricIT** [comment]
Can confirm that it works on my machine with the GitHub actions artefact!

**Comment by mmatyas** [comment]
Great! I guess this can be closed then.
